name: node-express-auth-boilerplate push to docker hub
run-name: ${{ github.actor }} pushing docker image to docker hub
on:
  push:
    branches: [ "master" ]
jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get branch name and Short SHA commit hash
        id: vars
        shell: bash
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-express-auth-boilerplate:${{ steps.vars.outputs.tag }}
          secrets: |
            API_PORT=${{ secrets.API_PORT }}
            API_HOST=${{ secrets.API_HOST }}
            BASE_API_ROUTE=${{ secrets.BASE_API_ROUTE }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            MONGO_URL=${{ secrets.MONGO_URL }}
            HASHING_ALGORITHM=${{ secrets.HASHING_ALGORITHM }}
            ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
            ACCESS_TOKEN_EXPIRY_TIME=${{ secrets.ACCESS_TOKEN_EXPIRY_TIME }}
            REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}
            REFRESH_TOKEN_EXPIRY_TIME=${{ secrets.REFRESH_TOKEN_EXPIRY_TIME }}
            VERIFY_TOKEN_SECRET=${{ secrets.VERIFY_TOKEN_SECRET }}
            VERIFY_TOKEN_EXPIRY_TIME=${{ secrets.VERIFY_TOKEN_EXPIRY_TIME }}
            RESET_PASSWORD_TOKEN_SECRET=${{ secrets.RESET_PASSWORD_TOKEN_SECRET }}
            RESET_PASSWORD_TOKEN_EXPIRY_TIME=${{ secrets.RESET_PASSWORD_TOKEN_EXPIRY_TIME }}
            CHANGE_PASSWORD_TOKEN_SECRET=${{ secrets.CHANGE_PASSWORD_TOKEN_SECRET }}
            CHANGE_PASSWORD_TOKEN_EXPIRY_TIME=${{ secrets.CHANGE_PASSWORD_TOKEN_EXPIRY_TIME }}
            "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}"
            "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}"
